# tests/test_app.py
import os
import datetime
import unittest

os.environ["TESTING"] = "true"
from app import app, mydb, TimelinePost

# Every page route in the app. Used for the render smoke test.
PAGE_ROUTES = [
    "/",
    "/jane",
    "/jane/hobbies",
    "/yanxi",
    "/yanxi/hobbies",
    "/yanxi/places",
    "/timeline",
]

class YanxiPortfolioTestCase(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        """Runs once before all tests."""
        app.config["TESTING"] = True

        if mydb.is_closed():
            mydb.connect()

        mydb.create_tables([TimelinePost], safe=True)

    def setUp(self):
        """Runs before each individual test."""
        self.client = app.test_client()

        # Start each test with an empty timeline table.
        TimelinePost.delete().execute()

    def tearDown(self):
        """Runs after each individual test."""
        TimelinePost.delete().execute()

    @classmethod
    def tearDownClass(cls):
        """Runs once after all tests finish."""
        mydb.drop_tables([TimelinePost], safe=True)

        if not mydb.is_closed():
            mydb.close()

    # Page rendering — status code + response type, not content
    def test_all_pages_render_html(self):
        """Every page returns 200, is HTML, and renders a non-empty body.

        This replaces the old per-string content assertions. It also catches
        templates that raise (which would 500) — something the old checks
        silently missed.
        """
        for path in PAGE_ROUTES:
            with self.subTest(path=path):
                response = self.client.get(path)

                self.assertEqual(response.status_code, 200)
                self.assertIn("text/html", response.content_type)
                self.assertGreater(len(response.get_data()), 0)

    # Structural links / navigation — app behavior, not resume data
    def test_home_page_links_to_each_portfolio(self):
        """Home page links out to both portfolio routes."""
        html = self.client.get("/").get_data(as_text=True)

        self.assertIn('href="/yanxi"', html)
        self.assertIn('href="/jane"', html)

    def test_yanxi_pages_render_shared_nav_menu(self):
        """The nav menu from ``yanxi_pages()`` appears on Yanxi's pages.

        These labels/links are generated by the app, so they're structure
        (safe to assert) rather than editable portfolio content.
        """
        for path in ["/yanxi", "/yanxi/hobbies", "/yanxi/places", "/timeline"]:
            with self.subTest(path=path):
                html = self.client.get(path).get_data(as_text=True)

                for label in ["About Me", "Hobbies", "Places", "Timeline"]:
                    self.assertIn(label, html)

                for href in [
                    'href="/yanxi"',
                    'href="/yanxi/hobbies"',
                    'href="/yanxi/places"',
                    'href="/timeline"',
                ]:
                    self.assertIn(href, html)

    # Timeline GET API — response type + schema
    def test_get_timeline_returns_json(self):
        response = self.client.get("/api/timeline_post")
        self.assertTrue(response.is_json)

    def test_get_timeline_has_timeline_posts_list(self):
        data = self.client.get("/api/timeline_post").get_json()
        self.assertIn("timeline_posts", data)
        self.assertIsInstance(data["timeline_posts"], list)

    def test_get_timeline_is_empty_initially(self):
        data = self.client.get("/api/timeline_post").get_json()
        self.assertEqual(data["timeline_posts"], [])

    def test_get_timeline_returns_existing_post_with_correct_types(self):
        TimelinePost.create(
            name="Visitor",
            email="visitor@example.com",
            content="Hello",
        )

        data = self.client.get("/api/timeline_post").get_json()
        posts = data["timeline_posts"]

        self.assertEqual(len(posts), 1)

        post = posts[0]
        # Check the shape/types of a serialized post, not specific values.
        for key in ["id", "name", "email", "content", "created_at"]:
            self.assertIn(key, post)

        self.assertIsInstance(post["id"], int)
        self.assertIsInstance(post["name"], str)
        self.assertIsInstance(post["email"], str)
        self.assertIsInstance(post["content"], str)

    def test_get_timeline_returns_multiple_posts(self):
        TimelinePost.create(name="A", email="a@example.com", content="1")
        TimelinePost.create(name="B", email="b@example.com", content="2")

        data = self.client.get("/api/timeline_post").get_json()

        self.assertEqual(len(data["timeline_posts"]), 2)

    def test_get_timeline_orders_newest_post_first(self):
        # Use explicit, distinct timestamps so ordering is deterministic and
        # doesn't depend on how close together the rows were created.
        older = TimelinePost.create(
            name="A", email="a@example.com", content="older",
            created_at=datetime.datetime(2020, 1, 1),
        )
        newer = TimelinePost.create(
            name="B", email="b@example.com", content="newer",
            created_at=datetime.datetime(2021, 1, 1),
        )

        posts = self.client.get("/api/timeline_post").get_json()["timeline_posts"]

        self.assertEqual(len(posts), 2)
        self.assertEqual(posts[0]["id"], newer.id)
        self.assertEqual(posts[1]["id"], older.id)

    # Timeline POST API — response type + schema + persistence
    def _valid_payload(self, **overrides):
        payload = {
            "name": "Portfolio Visitor",
            "email": "visitor@example.com",
            "content": "Great work!",
        }
        payload.update(overrides)
        return payload

    def test_create_timeline_post_returns_200(self):
        response = self.client.post(
            "/api/timeline_post", data=self._valid_payload()
        )

        # The app currently returns 200 on creation; 201 Created is the REST
        # convention if you decide to change it later.
        self.assertEqual(response.status_code, 200)

    def test_create_timeline_post_returns_json(self):
        response = self.client.post(
            "/api/timeline_post", data=self._valid_payload()
        )

        self.assertTrue(response.is_json)

    def test_create_timeline_post_returns_correct_shape(self):
        response = self.client.post(
            "/api/timeline_post", data=self._valid_payload(content="hi there")
        )
        data = response.get_json()

        # Echoed values.
        self.assertEqual(data["name"], "Portfolio Visitor")
        self.assertEqual(data["email"], "visitor@example.com")
        self.assertEqual(data["content"], "hi there")

        # Server-assigned fields exist and have the right types.
        self.assertIn("id", data)
        self.assertIn("created_at", data)
        self.assertIsInstance(data["id"], int)

    def test_create_timeline_post_saves_to_database(self):
        self.client.post(
            "/api/timeline_post", data=self._valid_payload(content="saved")
        )
        self.assertEqual(TimelinePost.select().count(), 1)

        saved = TimelinePost.get()
        self.assertEqual(saved.name, "Portfolio Visitor")
        self.assertEqual(saved.email, "visitor@example.com")
        self.assertEqual(saved.content, "saved")

    def test_created_post_appears_in_get_request(self):
        self.client.post(
            "/api/timeline_post",
            data=self._valid_payload(content="round trip"),
        )

        posts = self.client.get("/api/timeline_post").get_json()["timeline_posts"]

        self.assertEqual(len(posts), 1)
        self.assertEqual(posts[0]["content"], "round trip")

    def test_multiple_posts_have_different_ids(self):
        first = self.client.post(
            "/api/timeline_post", data=self._valid_payload(name="First")
        ).get_json()
        second = self.client.post(
            "/api/timeline_post", data=self._valid_payload(name="Second")
        ).get_json()

        self.assertNotEqual(first["id"], second["id"])

    # Invalid POST requests — status + error shape
    def test_post_without_name_returns_400(self):
        payload = self._valid_payload()
        del payload["name"]

        response = self.client.post("/api/timeline_post", data=payload)

        self.assertEqual(response.status_code, 400)

    def test_post_without_email_returns_400(self):
        payload = self._valid_payload()
        del payload["email"]

        response = self.client.post("/api/timeline_post", data=payload)

        self.assertEqual(response.status_code, 400)

    def test_post_without_content_returns_400(self):
        payload = self._valid_payload()
        del payload["content"]

        response = self.client.post("/api/timeline_post", data=payload)

        self.assertEqual(response.status_code, 400)

    def test_post_with_invalid_email_returns_400(self):
        response = self.client.post(
            "/api/timeline_post",
            data=self._valid_payload(email="no-at-sign"),
        )

        self.assertEqual(response.status_code, 400)

    def test_invalid_post_returns_json_error(self):
        payload = self._valid_payload()
        del payload["name"]

        response = self.client.post("/api/timeline_post", data=payload)

        self.assertTrue(response.is_json)
        self.assertIn("error", response.get_json())

    def test_invalid_post_does_not_save(self):
        payload = self._valid_payload()
        del payload["name"]

        self.client.post("/api/timeline_post", data=payload)

        self.assertEqual(TimelinePost.select().count(), 0)

    # Invalid routes and HTTP methods
    def test_unknown_page_returns_404(self):
        response = self.client.get("/yanxi/page-that-does-not-exist")

        self.assertEqual(response.status_code, 404)

    def test_timeline_api_rejects_delete_request(self):
        response = self.client.delete("/api/timeline_post")

        self.assertEqual(response.status_code, 405)


if __name__ == "__main__":
    unittest.main()